-- AlterTable
ALTER TABLE "public"."categories" ADD COLUMN     "meta_description_de" VARCHAR(500),
ADD COLUMN     "meta_description_es" VARCHAR(500),
ADD COLUMN     "meta_description_fr" VARCHAR(500),
ADD COLUMN     "meta_description_it" VARCHAR(500),
ADD COLUMN     "meta_description_ja" VARCHAR(500),
ADD COLUMN     "meta_description_ko" VARCHAR(500),
ADD COLUMN     "meta_title_de" VARCHAR(300),
ADD COLUMN     "meta_title_es" VARCHAR(300),
ADD COLUMN     "meta_title_fr" VARCHAR(300),
ADD COLUMN     "meta_title_it" VARCHAR(300),
ADD COLUMN     "meta_title_ja" VARCHAR(300),
ADD COLUMN     "meta_title_ko" VARCHAR(300),
ADD COLUMN     "seo_keywords_de" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seo_keywords_es" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seo_keywords_fr" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seo_keywords_it" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seo_keywords_ja" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seo_keywords_ko" TEXT[] DEFAULT ARRAY[]::TEXT[];
